apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hk9etodxu-nodejs 
  janus-idp.io/tekton: hk9etodxu-nodejs
  backstage.io/kubernetes-id: hk9etodxu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hk9etodxu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml