apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hk9etodxu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hk9etodxu-nodejs 
  name: hk9etodxu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hk9etodxu-nodejs 
